function setup()
 {
  createCanvas(1000,600);
  movement = floor(random()* 10);
}
  //practice commenting


//circle variables here
var x = 100;
var y = 200;
var diameter = 50;

//info for the circles
var movement = 13;

//title of drawing below
var size = 22;
var count = 0;
var sizeDirection = 2;

function draw() 
{
  background(220);
  square(350,200,200);
   circle(450,200,200);

//this below is an attempt to figure how to move the circles
circle(x,y,diameter)
if(x <= 900)
    {
        x+=13;
    }

circle(x,y,35)
if(x >= 800 || x <= 0)
    {
       movement *= -1;
    }

     x += movement;

circle(x, y, 27)
y++;


//below is the rest of what makes up the portrait 
  ellipse(400,200,50,50);
  ellipse(500,200,50,50);
stroke(100, 20, 20);
  rect(425,220,50,60);
  line(500, 300, 400, 350);
  point(500, 250);
  triangle(30, 75, 58, 20, 86, 75);
  strokeWeight(5);

//title of the drawing below called self portrait
textSize(size);
size+= sizeDirection;
count++;
if(count > 5)
{
   sizeDirection *=1;
   count = 0;
}
text('Self Portrait', 320, 50);


//this is just the signature below
textSize(40);
text('E.L', 500, 550);
} 

